eightball = [
        "Yeah 😑!",
        "Sure 😒!",
        "Nope 😒!",
        "Hell NO 😤!",
        "Pfff 😑!",
        "Unfortunately not",
        "You are disgustinly right!",
        "No, 🙂.",
        "I agree",
        "No idea!",
        "I am not at your level to answer that ..",
        "My sources say no!",
        "It is certain",
        "You can rely on it",
        "Probably not",
        "Everything points to a no",
        "No doubt",
        "Absolutely",
        "I do not know"
    ]
